#ifndef LILYPADS_COMMON_H
#define LILYPADS_COMMON_H

#define _GNU_SOURCE

#include "types.h"

/* ---- section: definitions ------------------------------------------------ */

#define NAME_MAX 256
#define STRING_MAX 2048
#define TEXT_WIDTH 80
#define LLP_CMT "--"

#define COL_NC_COEF 0.8
#define COL_NCL_COEF 0.9
#define TXT_NC_COEF 0.6
#define TXT_NCL_COEF 0.7

enum llp_color_index
{
    LLP_COLOR_NATURE_DARK,
    LLP_COLOR_NATURE_DARK_DEAD,
    LLP_COLOR_NATURE_LIGHT,
    LLP_COLOR_NATURE_LIGHT_DEAD,
    LLP_COLOR_CHERRY_DARK,
    LLP_COLOR_CHERRY_DARK_DEAD,
    LLP_COLOR_CHERRY_LIGHT,
    LLP_COLOR_CHERRY_LIGHT_DEAD,
    LLP_COLOR_OCEANS_DARK,
    LLP_COLOR_OCEANS_DARK_DEAD,
    LLP_COLOR_OCEANS_LIGHT,
    LLP_COLOR_OCEANS_LIGHT_DEAD,
    LLP_COLOR_COUNT
}; /* llp_color_index */

enum hl_group_sp_index
{
    HL_GROUP_SP_NONE,
    HL_GROUP_SP_BOLD,
    HL_GROUP_SP_UNDERLINE,
    HL_GROUP_SP_UNDERCURL,
    HL_GROUP_SP_UNDERDOUBLE,
    HL_GROUP_SP_UNDERDOTTED,
    HL_GROUP_SP_UNDERDASHED,
    HL_GROUP_SP_STRIKETHROUGH,
    HL_GROUP_SP_REVERSE,
    HL_GROUP_SP_INVERSE,
    HL_GROUP_SP_ITALIC,
    HL_GROUP_SP_STANDOUT,
    HL_GROUP_SP_ALTFONT,
    HL_GROUP_SP_DIM,
    HL_GROUP_SP_BLINK,
    HL_GROUP_SP_CONCEAL,
    HL_GROUP_SP_OVERLINE,
    HL_GROUP_SP_NOCOMBINE,
    HL_GROUP_SP_COUNT
}; /* hl_group_sp_index */

#endif /* LILYPADS_COMMON_H */
